version: '3.8'

services:
  # Neo4j Database
  neo4j:
    image: neo4j:4.4-community
    container_name: graphrag-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - graphrag-network

  # GraphRAG Application
  graphrag-app:
    build: .
    container_name: graphrag-app
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - neo4j
    networks:
      - graphrag-network
    restart: unless-stopped

  # Streamlit Web Interface
  streamlit:
    build: .
    container_name: graphrag-streamlit
    ports:
      - "8501:8501"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    command: streamlit run graphrag_streamlit.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - neo4j
    networks:
      - graphrag-network
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  graphrag-network:
    driver: bridge 