name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bandit
        run: pip install bandit
      - name: Print Bandit version
        run: bandit --version
      - name: Run Bandit and capture output
        run: |
          bandit -r . -f sarif -o bandit-report.sarif > bandit-output.log 2>&1 || true
          echo "Bandit run completed. Listing files:"
          ls -l
      - name: Check for SARIF file and print Bandit output if missing
        run: |
          if [ ! -f bandit-report.sarif ]; then
            echo "SARIF report not found! Printing Bandit output:";
            cat bandit-output.log;
            exit 1;
          fi
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit-report.sarif 